Profile
team-ful/noratomo pull request #112
Opened 2022-07-18 07:59 UTC by Sottiki

- issue:

## 🔧 修正点

## ✅ 自己チェック

- [ ] 動作確認ができているか
- [ ] 新しく追加したメソッドにユニットテストを追加しているか
- [ ] 静的解析、テストは成功しているか
- [ ] `Files changed`を自分で確認してミスがないか

## 📸 スクリーンショット（オプション）

## ⚠️ レビュー時に注意して欲しいこと（オプション）

## 🗣️ 補足など（オプション）

2022-07-22 10:54 UTC, cateiru commented on components/Frame/Frame.tsx
> +    } else if (/\/profile\/?.*/g.test(router.pathname)) {
```suggestion
    } else if (router.pathname === "/profile")) {
```

2022-07-22 11:01 UTC, cateiru requested changes

2022-07-22 11:01 UTC, cateiru commented on components/Profile/ProfileMenu.tsx
> +        <Box width={{base: '700px', sm: '100%'}}>
700pxじゃなくてももう少し小さくても良いかも

2022-07-22 11:01 UTC, cateiru commented on components/Profile/UserProfile.tsx
> +      <Text m="2rem 1rem">{user?.profile}</Text>
これ多分、改行効かない。。。

preにしたい。
```suggestion
      <Text m="2rem 1rem" as="pre">{user?.profile}</Text>
```

2022-07-23 04:49 UTC, Sottiki commented on components/Frame/Header.tsx
> +                zIndex="1"
機能プロフィール機能を実装してもらってからもう一度試してみたけど、
zIndexを消した状態で、レスポンシブでスマホ用くらいに狭くなるとプロフィールに遷移するボタン（自分のアイコン）と、noratomoロゴ（ホームに遷移するやつ）も効かなくな流みたいです。

2022-07-23 04:49 UTC, Sottiki commented on components/Frame/Frame.tsx
> +            flexDirection="column"
ディレクション切ると何故か左によってしまう
![localhost_3000_profile(フルスクリーン) (1)](https://user-images.githubusercontent.com/81673075/180590746-a77eb98c-94fb-4a95-8e2b-faeca838187f.png)
こんな感じで。。。

2022-07-23 04:49 UTC, Sottiki commented on components/Frame/Frame.tsx
> +    } else if (router.pathname === "/profile")) {
このパスの判定でプロフィール画面に飛んだ時に、初めの状態ではタブが表示されるのですが
タブを押した後にタブが表示されなくなっちゃいます
![localhost_3000_profile_mygood](https://user-images.githubusercontent.com/81673075/180590823-c6c1f481-55a8-47b3-9b30-b75b941dbff5.png)
こんな感じです。。。
そうしたらいいですかね。。。

2022-07-23 04:58 UTC, Sottiki commented on components/Frame/Frame.tsx
> +            flexDirection="column"
機能実装し終わってもう一度試してみたのですが、レスポンシブで幅を細くしたときにやはりヘッダーのボタンの部分（noratomoロゴのホームボタン含め）が効かなくなってしまうようです。。。

2022-07-23 05:08 UTC, Sottiki commented on components/Frame/Frame.tsx
> +    } else if (/\/profile\/?.*/g.test(router.pathname)) {
これを反映して確認してみたのですが、
タブを押した後にタブが表示されなくなってしまいました。
![localhost_3000_profile_mygood](https://user-images.githubusercontent.com/81673075/180591126-b25c1b65-6738-4240-935d-ea1a07612114.png)
こんな感じです。。。どうしたら良いでしょうか

2022-07-23 05:12 UTC, Sottiki commented on components/Frame/Header.tsx
> +                zIndex="1"
機能実装し終わってもう一度試してみたのですが、レスポンシブで幅を細くしたときにやはりヘッダーのボタンの部分（noratomoロゴのホームボタン含め）が効かなくなってしまうようです。。。

2022-07-23 05:48 UTC, cateiru commented on components/Frame/Frame.tsx
> +            flexDirection="column"
nrhd

2022-07-23 05:56 UTC, cateiru commented on components/Frame/Frame.tsx
> +    } else if (/\/profile\/?.*/g.test(router.pathname)) {
あーーー正規表現のままで良かったすまぬ

2022-07-23 05:58 UTC, cateiru commented on components/Frame/Header.tsx
> +                zIndex="1"
positionを使っていないので、問題はz-index以外では？

2022-07-24 08:26 UTC, cateiru approved these changes
良さそう

2022-07-25 05:53 UTC, merged