Get login history
team-ful/noratomo pull request #141
Opened 2022-08-15 08:13 UTC by Sottiki

- issue:
https://github.com/team-ful/noratomo/issues/90
## 🔧 修正点

## ✅ 自己チェック

- [ ] 動作確認ができているか
- [ ] 新しく追加したメソッドにユニットテストを追加しているか
- [ ] 静的解析、テストは成功しているか
- [ ] `Files changed`を自分で確認してミスがないか

## 📸 スクリーンショット（オプション）

## ⚠️ レビュー時に注意して欲しいこと（オプション）

## 🗣️ 補足など（オプション）

2022-08-15 11:28 UTC, cateiru commented
みます

2022-08-15 11:48 UTC, cateiru requested changes
スマホで見たのでガバガバですが一応……

2022-08-15 11:48 UTC, cateiru commented on components/Frame/Header.tsx
> +        </NextLink>
ここは良さそうだけど、スクリーンショットあるともっと良さそうです！

2022-08-15 11:48 UTC, cateiru commented on components/History/ALoginHistory.tsx
> +import {LoginHistoryUserInfo} from '../../utils/types';
Info…？なのかな…？elementとかの方が良かったりしそう？

2022-08-15 11:48 UTC, cateiru commented on components/History/ALoginHistory.tsx
> +  const date = data.login_date.toString();
toStringってどうなんでしょう？

2022-08-15 11:48 UTC, cateiru commented on components/History/ALoginHistory.tsx
> +import {Td, Tr} from '@chakra-ui/react';
ALoginHistoryってどうなんだろう…？aって単一のものだからログイン履歴が1つしかないみたいにならない？

2022-08-15 11:48 UTC, cateiru commented on components/History/LoginHistories.tsx
> +  const res = useGetLoginHistories();
変数名resは情報量無さすぎてなんなのか分からなさそう。

2022-08-15 11:48 UTC, cateiru commented on components/Session/useGetLoginHistories.tsx
> +  f();
これだと、レンダリング毎に毎回fetchしちゃわない？

2022-08-15 11:48 UTC, cateiru commented on components/Session/useGetLoginHistories.tsx
> +    const data = (await res.json()) as LoginHistoryUserInfo[];
レスポンスが200以外の処理もあった方が良さそう

2022-08-15 11:48 UTC, cateiru commented on package.json
> +
？

2022-08-15 11:48 UTC, cateiru commented on pages/api/user/login_history.ts
> + * ログイン履歴を過去50件まで取得する
limitで指定できるなら50件では無さそう？

2022-08-15 11:48 UTC, cateiru commented on pages/api/user/login_history.ts
> +    parseInt(limit || 'undefined')
parseIntは不正な値の場合NaNになると思うんですけどその場合の挙動とかどうなるんだろう

2022-08-15 11:48 UTC, cateiru commented on pages/api/user/login_history.ts
> +    throw new ApiError(500, 'error');
500はログイン履歴は必ずある必要があるので良さそうだけど、エラーメッセージが情報量ないので意味ある文言にすると良さそう

2022-08-15 11:48 UTC, cateiru commented on pages/api/user/login_history.ts
> + * @param {AuthedBase<void>} base base
```suggestion
 * @param {AuthedBase<void>} base - base
```

2022-08-15 11:48 UTC, cateiru commented on pages/history/login_histories.tsx
> +// pages/history/login_histories
このコメントはいらなそう？

2022-08-15 11:48 UTC, cateiru commented on src/base/authedBase.ts
> +  // }
削除！！

2022-08-15 11:48 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +      expect(history2[0].login_date >= history2[49].login_date).toBeTruthy();
+でorderByが正しいか（最新のやつから取得できているか）のテストがあると良さそう

2022-08-15 11:48 UTC, cateiru commented on utils/atom.ts
> +export const LoginHistoryUserInfoState = atom<LoginHistoryUserInfo | null>({
Recoil使っとるん？そしたらキャッシュ効くようにちゃんとfetchしたほうがええな

2022-08-15 11:48 UTC, cateiru commented on utils/types.ts
> +import {Device} from '../src/base/base';
ここ、srcはバックエンド側の実装なのでimportしたくないです

2022-08-16 07:36 UTC, Sottiki commented on components/Frame/Header.tsx
> +        </NextLink>
スクショ貼りました！

2022-08-17 00:42 UTC, Sottiki commented on components/History/ALoginHistory.tsx
> +  const date = data.login_date.toString();
toString()を使わない方がいい理由調べてみたんだけど、規格依存があるからって事であってるますか？
それとも、単に表示する情報が多すぎて分かりづらいからParseのやつ使った方がいいって感じかな。

2022-08-17 12:53 UTC, cateiru commented
さっと見るか

2022-08-17 13:07 UTC, cateiru commented
https://github.com/team-ful/noratomo/pull/141#discussion_r945643329 ?

2022-08-17 13:26 UTC, cateiru requested changes
みました。1つ修正し忘れあるかと思います。

2022-08-17 13:26 UTC, cateiru commented on components/History/LoginHistoryItems.tsx
> +      <Td>{date}</Td>
スクショ見たんですけど、これ読み解くの難しくないですか？

子供やお年寄りがみるというケースを想像したときに絶対日時は結構つらいのでは？と思います。○日前とかで表示できるといいと思いました。絶対日時はTooltipでカーソル合わせると表示されるようにすると尚良しかと思います。

便利なメソッド存在します。

- 相対日時: https://github.com/team-ful/noratomo/blob/main/utils/parse.ts#L47
- 日本語絶対日時: https://github.com/team-ful/noratomo/blob/main/utils/parse.ts#L26

2022-08-17 13:26 UTC, cateiru commented on components/History/LoginHistoryItems.tsx
> +      <Td>{data.device_name}</Td>
これも、子供が`Desktop`というスペルを見たというケースを考えたときにそれが正しくデスクトップPCであると想像できなさそうな気がします。

アイコンで表示されるようにするのはどうでしょうか？また、デバイス名以外にもOSやブラウザ名も存在する場合もあると思いますがそちらは表示されない？？

2022-08-17 13:26 UTC, cateiru commented on pages/api/user/login_history.ts
> +  const parse_limit = parseInt(limit || 'undefined');
camelCase

2022-08-17 13:26 UTC, cateiru commented on pages/api/user/login_history.ts
> +  if (isNaN(parse_limit)) {
[雑談]

ほええーーー`Number.`いらないんか初めて知った

https://stackoverflow.com/questions/33164725/confusion-between-isnan-and-number-isnan-in-javascript

なるほどーーーー内部実装すこし違うから引数がnumber以外の挙動変わってくるのか。まあ、今回はparseInt後だから特に問題はなさそう。

2022-08-17 13:26 UTC, cateiru commented on pages/api/user/login_history.ts
> +  const loginHistory = await findLoginHistoriesByUserID(
loginHistoriesかな？

2022-08-17 13:26 UTC, cateiru commented on pages/api/user/login_history.ts
> +  }
思ったんだけど、Arrayで返すならnullじゃなくて空配列でよくない？

2022-08-17 13:26 UTC, cateiru commented on src/base/authedBase.ts
> +
?

2022-08-17 13:26 UTC, cateiru commented on components/Frame/Header.tsx
> +
謎の空白行

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +      ) VALUES (?, INET_ATON(?), ?, ?, DATE_ADD(now(), INTERVAL ${i} HOUR))`,
`${i}`は?にしてください。テストだから大丈夫だろうというルールにすると絶対どこかでほころびが起きそうです。

なぜだめなのかはSQL インジェクションで検索！！

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    for (let i = 0; 50 > i; i++) {
50個も作成するなら、multiple insertにしたほうがいいかも

https://csnw.github.io/sql-bricks/#insert

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    const re_history = await findLoginHistoriesByUserID(base.db, userID, 2);
camelCase

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    const history2 = await findLoginHistoriesByUserID(base.db, userID);
`history2`は情報量ないかと…

`historyUnspecifiedLimit` とか？

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    if (history2 && re_history) {
念には念を入れてelseでthrow new Errorするとよさそう

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    //もう１０件ログインをバラバラに追加して、最新のログインから取得できているか調べる。
```suggestion
    //もう10件ログインをバラバラに追加して、最新のログインから取得できているか調べる。
```

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    for (let i = 0; 10 > i; i++) {
これはメソッド分けたほうが良さそう

2022-08-17 13:26 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +      ).toBeTruthy();
何件取得できているかのテストは上ですでにやっているのでこれは冗長？降順で取得できているかのテストだけで良さそう。

2022-08-17 13:26 UTC, cateiru commented on utils/atom.ts
> +    default: undefined,
これだと型が`LoginHistoryUserElements | null | undefined`にならないか？

2022-08-17 14:12 UTC, Sottiki commented on components/History/LoginHistoryItems.tsx
> +      <Td>{date}</Td>
スクショ更新し忘れてました。申し訳ないです。
今回は教えもらったパースのやつ使って、相対日時で表示してます。

2022-08-17 14:17 UTC, cateiru commented on components/History/ALoginHistory.tsx
> +  const date = data.login_date.toString();
ごめん、言葉足らずだった。toStringの戻り値って基本ユーザに見せるものではなくデバッグなどで使用するようなものだと思うので、ここで使うのはちょっと検討したほうがよさそうということでした。

2022-08-18 13:01 UTC, Sottiki commented on components/History/ALoginHistory.tsx
> +  const date = data.login_date.toString();
なるほど！勉強になります。ありがとう。

2022-08-18 13:11 UTC, Sottiki commented on components/History/LoginHistoryItems.tsx
> +      <Td>{data.device_name}</Td>
募集して知らない他人と会うという時点で、Desctopという単語を理解できなレベルの子供であればそもそもこのサービスは使わない方が良いというか、サービスの対象外と認識していました。
しかし、見づらいのは確かなので、おっしゃっている通り、OS・ブラウザも表示したりアイコンは使うべきだと思います。
その方針で実装し直そうと思います。ありがとうございます。

2022-08-24 14:30 UTC, cateiru commented on components/History/LoginHistories.tsx
> +                  <Center>ログイン日時</Center>
いかにも`text-aligin: center`使えそう

2022-08-24 14:30 UTC, cateiru commented on components/History/LoginHistoryItems.tsx
> +          {data.browser_name} / {data.os}
型情報を見ると`device_name`, `browser_name`, `os`はnullになる可能性があると思います。その場合の描画方法も指定したほうがよさそう。

[Null 合体演算子 (??) - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2022-08-24 14:30 UTC, cateiru commented on components/Session/useGetLoginHistories.tsx
> +};
これだけならわざわざhooksにする必要は無いかも？

2022-08-24 14:30 UTC, cateiru commented on pages/api/user/login_history.ts
> +  }
ふと思ったんだけど、parseIntってundefined返すんだっけ…？Numberしか返さなさそう？

2022-08-24 14:30 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +import SqlBricks from 'sql-bricks';
```suggestion
import sql from 'mysql-bricks';
```

2022-08-24 14:30 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +    const sql = SqlBricks;
```suggestion

```

2022-08-24 14:30 UTC, cateiru commented on utils/atom.ts
> +export const LoginHistoryUserElementsState = atom<LoginHistoryUserElements>({
使ってないなら消して良さそう

2022-08-25 08:52 UTC, Sottiki commented on pages/api/user/login_history.ts
> +  }
limitが正しく整数変換できないとparseIntはNaNを返すらしい。
limit自体が、string | undefined　なのでエラーが出ていてこうしといたのですが、
コンパイルし直したら、なぜかundefinedのエラー消えたので外しておきます。

2022-08-25 09:39 UTC, cateiru commented on pages/api/user/login_history.ts
> +  }
これだと、limit指定が必須で、存在しないとエラーになるような気がする

2022-08-25 11:01 UTC, Sottiki commented on pages/api/user/login_history.ts
> +  }
今確認したら、書き方間違えてて再びエラー出ました。
確かにそうか、、、
有難うござい！

2022-08-27 07:11 UTC, cateiru approved these changes
見ました。まだ修正されてないやつあるっぽい

2022-08-27 07:11 UTC, cateiru commented on components/History/DeviceIcon.tsx
> +          <Tooltip label="スマートフォン" placement="top">
ここのTooltipも角丸めよう

2022-08-27 07:11 UTC, cateiru commented on components/History/LoginHistories.tsx
> +  };
ん？ん？ん？`const {data, error} = useSWR<LoginHistoryUserElements[], string>...`だけでいいのでは？？？？

2022-08-27 07:11 UTC, cateiru commented on components/History/LoginHistories.tsx
> +  if (typeof loginHistories.data === 'undefined') {
ここはローディング中なので、スケルトンやらスピナーやらを表示させたほうがいいと思う。

2022-08-27 07:11 UTC, cateiru commented on components/History/LoginHistoryItems.tsx
> +          {data.browser_name ?? '不明なブラウザ'} / {data.os ?? '不明なOS'}
結局OSとブラウザは同じ列に表示させるんだっけ？

2022-08-27 07:11 UTC, cateiru commented on pages/api/user/login_history.ts
> +  if (limit) {
limit=0 で指定したときのテスト追加してみ、反映されないと思う

2022-08-27 07:11 UTC, cateiru commented on pages/api/user/login_history.ts
> +    base.sendJson(d);
これ2個あるのよくないですね笑

2022-08-27 07:11 UTC, cateiru commented on pages/history/login_histories.tsx
> +const Login_histories: NextPage = () => {
No snake_case

2022-08-27 07:11 UTC, cateiru commented on tests/pages/api/user/login_history.test.ts
> +        if (res.status && base.users[0].user?.id) {
このifがfalseのときはテスト実行しないようになってない？elseでthrowしない？

2022-08-27 07:11 UTC, cateiru commented on tests/pages/api/user/login_history.test.ts
> +          expect(await res.json()).toStrictEqual(JSON.parse(dJson));
これは、なぜそうしているのかコメントかけると良さそう

2022-08-27 07:11 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +import SqlBricks from 'sql-bricks';
？？ まだ修正されてない

2022-08-27 07:11 UTC, cateiru requested changes
ミスった

2022-08-27 07:18 UTC, Sottiki commented on components/History/LoginHistoryItems.tsx
> +          {data.browser_name ?? '不明なブラウザ'} / {data.os ?? '不明なOS'}
読み逃してました、修正します！

2022-08-27 14:38 UTC, Sottiki commented on pages/api/user/login_history.ts
> +  if (limit) {
limit="0" の時は,if文がfalseになるからlimit引数なしで50個帰ってきちゃうってこと？
0にすると、50個帰ってくる。findByUserIDの方は limit ?? 50だからlimit=0で50帰ってくるのは当然かなと思ったんだけど、
handlerのテストの方は,ログイン履歴を大量に作って試してるけど、確かにうまくいかないや。
apiにクエリがうまく渡せてないのかな

2022-08-27 14:56 UTC, cateiru commented on pages/api/user/login_history.ts
> +  if (limit) {
??はnull合体演算子だから、0の時は0が返ってくるんじゃない？

2022-08-27 15:26 UTC, Sottiki commented on pages/api/user/login_history.ts
> +  if (limit) {
恥ず、そうでした。
でも、結局、if文でfalseになっちゃうので,limit引数なしでfindByしてデフォルトの50個が帰ってくるってことよね。
limit="0"を指定されたらエラー返したりする方が実装としては良いんですかね？

2022-08-28 06:52 UTC, cateiru commented on pages/api/user/login_history.ts
> +  if (limit) {
んーーーlimit=0だったらそのまま0でクエリ叩いてしてしまっていいかもしれない。→ `typeof limit !== 'undefined'`

もし、心配であればlimitが1より小さい自然数の場合はエラースローさせるようにしてもいいかも。

2022-08-29 12:45 UTC, cateiru commented on components/History/LoginHistories.tsx
> +  isLoading = false;
これで動くのマジか！！！！

と思ったけど、useSWRの戻り値はstateだと思うから非同期なのでは？
なので、この`isLoading`はfetchが終わっているかどうかにかかわらず一瞬でtrue->falseになると思われる（デバッグしていないので想像です）

普通に`if (typeof data === 'undefined') {`のDOMにロード時のなにかを書いてほしかった。

ref. https://zenn.dev/ikenohi/articles/4a4d659e80237b

2022-08-29 12:57 UTC, cateiru requested changes
mimasita

2022-08-29 12:57 UTC, cateiru commented on pages/api/user/login_history.ts
> + * 引数を指定しない場合は、デフォルトで５０件まで。
```suggestion
 * 引数を指定しない場合は、デフォルトで50件まで。
```

数字は半角にしようZE！！！

2022-08-29 12:57 UTC, cateiru commented on pages/api/user/login_history.ts
> +    const parseLimit = parseInt(limit);
[memo] parseIntなのですべて整数になるから小数点は考えなくてよい

2022-08-29 12:57 UTC, cateiru commented on tests/pages/api/user/login_history.test.ts
> +          JsonはDateの区別をしないので、日付が違う形式に変換された上でStringとして処理される。
日付が違う形式 → [ISO 8601](https://ja.wikipedia.org/wiki/ISO_8601)

2022-08-30 06:33 UTC, cateiru commented on components/History/LoginHistories.tsx
> +      <Box>
[may] Boxは不要かも

2022-08-30 07:27 UTC, Sottiki commented on components/History/LoginHistories.tsx
> +      <Box>
何の意味も成してないですね。。。すみません

2022-08-30 15:17 UTC, cateiru requested changes

2022-08-30 15:17 UTC, cateiru commented on src/services/loginHistory.ts
> +    return rows.map(v => new LoginHistory(v));
一番上で `if(limit === 0} return []`してしまったほうがいいかも

2022-08-30 15:17 UTC, cateiru commented on tests/service/loginHistory.test.ts
> +  test('最新のログインから取得できている', async () => {
これはserviceのテストですでに実施しているので不要ですね

2022-08-30 15:17 UTC, cateiru commented on components/History/LoginHistories.tsx
> +  } else {
ifブロック内でreturnしているのにelseを書くのは冗長なように感じます。

2022-08-31 07:48 UTC, cateiru approved these changes
良さそうです。お疲れさまでした 🎉

2022-08-31 08:13 UTC, merged