お問い合わせ機能の実装
team-ful/noratomo pull request #150
Opened 2022-09-05 13:44 UTC by Sottiki

- issue:

## 🔧 修正点

## ✅ 自己チェック

- [ ] 動作確認ができているか
- [ ] 新しく追加したメソッドにユニットテストを追加しているか
- [ ] 静的解析、テストは成功しているか
- [ ] `Files changed`を自分で確認してミスがないか

## 📸 スクリーンショット（オプション）

## ⚠️ レビュー時に注意して欲しいこと（オプション）

## 🗣️ 補足など（オプション）

2022-09-07 08:10 UTC, cateiru requested changes
み！！！！！

2022-09-07 08:10 UTC, cateiru commented on components/Contact/Contact.tsx
> +    }
サーバー側でログインしていないときに301でリダイレクトすればスマートかもって思ったけど。これでも問題なさそう。

2022-09-07 08:10 UTC, cateiru commented on components/Contact/Contact.tsx
> +              <option value="4">その他</option>
ここは、デザイナーさんと相談しましょう

2022-09-07 08:10 UTC, cateiru commented on pages/api/contact/contact.ts
> +// src/services/sendContact.ts にデータを転送する
いらなそう？

2022-09-07 08:10 UTC, cateiru commented on pages/api/contact/no_login.ts
> +// src/services/sendContact.ts にデータを転送する
ここも

2022-09-07 08:10 UTC, cateiru commented on src/services/conatact/sendUserContact.ts
> +export async function contactUserHandler(abase: AuthedBase<void>) {
```suggestion
export async function contactUserHandler(base: AuthedBase<void>) {
```

2022-09-07 08:10 UTC, cateiru commented on src/services/conatact/sendContact.ts
> +    //components/Admin/Notice.tsx
消して良さそう

2022-09-07 08:10 UTC, cateiru commented on src/services/conatact/sendContact.ts
> +// Contacts.tsx -> Contact.tsx(フォームデータを転送) -> contact.ts(pages/api:handler) -> sendContact.ts(src/service:データを整形してPOSTする) -> discode
同じく

2022-09-07 08:10 UTC, cateiru commented on src/services/conatact/sendUserContact.ts
> +}
ここらへんの処理、`contactHandler`と同じっぽいので共通化してもいいかもしれないです。

例えば、`sendDiscord(text: string): Promise<void>`みたいな関数を作ってしまったり。。。

書体も、embedなど使ってわかりやすくしませんか？

https://qiita.com/Eai/items/1165d08dce9f183eac74

https://discohook.org/

2022-09-07 08:10 UTC, cateiru commented on src/services/conatact/sendUserContact.ts
> +}
なんならDiscordクラスみたいなのを`src/service/api`に作ってしまってもいいかもしれないです。

2022-09-07 08:20 UTC, Sottiki commented on src/services/conatact/sendUserContact.ts
> +}
ほほう！やってみます！

2022-09-23 13:12 UTC, cateiru requested changes
みました！もう少し！！

2022-09-23 13:12 UTC, cateiru commented on tests/contact/contactHandler.test.ts
> +  const base: TestBase = new TestBase();
```suggestion
  const base = new TestBase();
```

型ヒント書かなくてもわかるかも？

2022-09-23 13:12 UTC, cateiru commented on tests/contact/contactHandler.test.ts
> +    await u.addSession(base.db);
これは26行目ですでに呼ばれていそう

2022-09-23 13:12 UTC, cateiru commented on tests/contact/contactHandler.test.ts
> +  });
これ、テストごとに指定しないと`.toHaveLastFetched`が意味をなさないんじゃないかな？
`.toHaveLastFetched`は呼ばれたとこを見るからすでに1度読んでしまえば必ず成功しそう。

2022-09-23 13:12 UTC, cateiru commented on tests/contact/contactHandler.test.ts
> +    await u.addSession(base.db);
ここも消して良さそう

2022-09-30 04:25 UTC, cateiru approved these changes
良さそうでした！お疲れさまでした！！

2022-09-30 04:29 UTC, cateiru commented
本番用に`DISCORD_CONTACT_URL`環境変数の値を設定したのでマージしてしまって大丈夫です。 to. @Sottiki

2022-09-30 05:55 UTC, Sottiki commented
> 良さそうでした！お疲れさまでした！！

TY!!

2022-09-30 05:56 UTC, merged