チャットアイコンを猫のアイコンに変更.
team-ful/noratomo pull request #70
Opened 2022-06-19 05:51 UTC by Sottiki

- issue:

## 🔧 修正点

## ✅ 自己チェック

- [ ] 動作確認ができているか
- [ ] 新しく追加したメソッドにユニットテストを追加しているか
- [ ] 静的解析、テストは成功しているか
- [ ] `Files changed`を自分で確認してミスがないか

## 📸 スクリーンショット（オプション）

## ⚠️ レビュー時に注意して欲しいこと（オプション）

## 🗣️ 補足など（オプション）

2022-06-19 08:06 UTC, cateiru requested changes
スクショだけ欲しいです！

2022-06-19 08:49 UTC, Sottiki commented
スクショ追加しておきました。こんな感じです。

2022-06-19 09:01 UTC, cateiru approved these changes
良さそう

2022-06-20 01:53 UTC, cateiru commented
これ、マージしてしまいますね

2022-06-20 01:53 UTC, merged