Toolbar実装と装飾
team-ful/noratomo pull request #87
Opened 2022-06-30 08:10 UTC by Sottiki

- issue:

## 🔧 修正点

## ✅ 自己チェック

- [ ] 動作確認ができているか
- [ ] 新しく追加したメソッドにユニットテストを追加しているか
- [ ] 静的解析、テストは成功しているか
- [ ] `Files changed`を自分で確認してミスがないか

## 📸 スクリーンショット（オプション）
<img width="330" alt="スクリーンショット 2022-06-30 17 08 50" src="https://user-images.githubusercontent.com/81673075/176626562-993e3810-025b-4a27-9e50-792823aaf710.png">

## ⚠️ レビュー時に注意して欲しいこと（オプション）

## 🗣️ 補足など（オプション）

2022-06-30 08:37 UTC, cateiru commented on components/Frame/Header.tsx
> +          mx="2rem"
1rem版もスクショ欲しい！比較したい！

2022-06-30 08:40 UTC, cateiru commented
ちなみにPayPayカードのページのツールバーはこんな感じ

![image](https://user-images.githubusercontent.com/24271196/176632974-af595d82-8625-43e8-9095-c88c271152db.jpeg)

2022-06-30 09:05 UTC, cateiru commented on components/Frame/Header.tsx
> +          boxShadow="-5px 5px 14px #969696"
@itooooosangred あ、動作確認じゃなくてデザイン周りの確認って意味です！！！

2022-06-30 09:50 UTC, itooooosangred commented on components/Frame/Header.tsx
> +          boxShadow="-5px 5px 14px #969696"
スクショ欄の画像で合っているなら、確かに影をもう少し薄くしてもいいかもしれない
ぱっと見個人的にはスクショ画像の影の濃さの75%ぐらいでどうですか

2022-06-30 10:21 UTC, MONENEN commented on components/Frame/Header.tsx
> +          boxShadow="-5px 5px 14px #969696"
枠のサイズを大きくして文字を上か下に書いてもいいかもしれないですね
後もっと下に設置した方が誤タップしないし邪魔にならなそう

2022-06-30 10:39 UTC, Sottiki commented on components/Frame/Header.tsx
> +          columns={9}
これ５にすると、なんかギザギザになるのよね。。。

2022-06-30 10:46 UTC, Sottiki commented on components/Frame/Header.tsx
> +          borderRadius="15px"
100%だと楕円になるので、50pxにしとくでやんす

2022-06-30 10:57 UTC, Sottiki commented on components/Frame/Header.tsx
> +        </Flex>
確かに。これは別ブランチでやるとする。
ついでに、アイコン下にラベル表示できる様にします。

2022-06-30 11:01 UTC, Sottiki commented on components/Frame/Header.tsx
> +          columns={9}
ごめん、解決した。
<spacer>が入ったままでした。

2022-06-30 11:28 UTC, cateiru commented on components/Frame/Header.tsx
> +        </Flex>
このブランチでやりましょ

2022-06-30 14:13 UTC, Sottiki commented
2remバージョン
<img width="330" alt="スクリーンショット 2022-06-30 23 10 48" src="https://user-images.githubusercontent.com/81673075/176699716-53d20056-fd5f-465a-bbd3-18e7713608e7.png">
1remバージョン
<img width="330" alt="スクリーンショット 2022-06-30 23 10 11" src="https://user-images.githubusercontent.com/81673075/176699724-a0c4bbfe-da4f-42b3-b071-0ab3a6656fd6.png">

2022-06-30 14:18 UTC, cateiru commented
1remのほうがよさそう。説明文あるのもgood

2022-06-30 14:28 UTC, cateiru requested changes
もう少し！！！あと、下に文字あるならアイコンサイズもう少し小さい方が良い？

2022-06-30 14:28 UTC, cateiru commented on components/Logo/IconChat.tsx
> +    <Tooltip label={label}>
これlabelが指定されてない時でもコンポーネントあるの良くなさそう。

やるとしたらlabelで三項演算子使ってコンポーネント自体表示しない方が良さそう

2022-06-30 14:28 UTC, cateiru commented on components/Logo/IconChat.tsx
> +        <svg
アイコンは単体で使用する可能性があるのでアイコンだけでコンポーネント作ってください

2022-06-30 14:28 UTC, cateiru commented on components/Logo/IconChat.tsx
> +  iName?: string;
iconのコンポーネントとラベルとisTooltipのフラグをpropsで渡せるコンポーネントを1つ作成するだけで良さそうな気がします。

例:

```tsx
<MenuButton icon={<HomeIcon size="25px">} label="ホーム" isTooltip href="/" />
```

2022-06-30 14:50 UTC, Sottiki commented
なるほど。。。🤔

2022-07-01 02:49 UTC, cateiru commented on components/Logo/IconChat.tsx
> +  iName?: string;
なぐり書きだから間違っているかもしれないけどこんな感じの実装でできそう

```tsx
import React from 'react';
import NextLink from 'next/link';
import {Link, Tooltip} from '@chakra-ui/react';

interface Props {
  icon: React.ReactNode,
  label: string,
  isTooltip: boolean,
  href: string
};

const MenuButton: React.FC<Props> = ({icon, label, isTooltip, href}) => {
  const MenuLink: React.FC<{children: React.ReactNode}> = ({children}) => {
    return (
      <NextLink passHref href={href}>
        <Link>{children}</Link>
      </NextLink>
    );
  }

  if(isTooltip) {
    return (
      <Tooltip label={label}>
        <MenuLink>
          {icon}
        </MenuLink>
      </Tooltip>
    );
  }

    return (
      <MenuLink>
          {icon}
        <Text>{label}</Text>
      </MenuLink>
    );
}
```

2022-07-01 06:34 UTC, Sottiki commented on components/Logo/IconChat.tsx
> +  iName?: string;
ありがとう
目星がこんな感じだったので、実装方法明確になりました。

2022-07-01 10:18 UTC, cateiru approved these changes
めちゃよい

2022-07-01 10:27 UTC, merged